language: node_js
node_js:
- 0.1
deploy:
  provider: npm
  email: k4rim.sa@gmail.com
  api_key:
    secure: JJe4yS197Ucy5Kq1tX8/bm3rN/DjPy8GLWZhLFFu+IfphiZmU5orBUkXbFOgNn6qcFieEQQSltwreKXtgmjGyTSWdfZ8nb9a3M0ipEnCCjxsDnyT+yc1DY/Dmnlw89DsQXiMHwRVDkb2/JZd4hLYy64SyMslaNW7t7CFjIyoEsY=
  on:
    repo: karimsa/gulp-jslint
    tags: true
